# Generated by Django 4.2.30 on 2026-07-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_course_session_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                ("grade", models.CharField(blank=True, default="", max_length=20, verbose_name="年级")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="courses.major",
                        verbose_name="所属专业",
                    ),
                ),
            ],
            options={
                "db_table": "class_group",
                "ordering": ["major", "grade", "name"],
                "unique_together": {("name", "major")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="courses.classgroup",
                verbose_name="所属班级",
            ),
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "grade",
                    models.CharField(
                        blank=True, default="", help_text="目标年级，如 2024（为空表示不限年级）", max_length=20
                    ),
                ),
                (
                    "class_identification",
                    models.CharField(
                        blank=True, default="", help_text="目标班级，如 计科2401（为空表示不限班级）", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="courses.course"
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        help_text="目标专业（为空表示不限专业）",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.major",
                    ),
                ),
            ],
            options={
                "db_table": "course_assignment",
                "ordering": ["-created_at"],
                "unique_together": {("course", "major", "grade", "class_identification")},
            },
        ),
    ]
